### PR TITLE
Lots of commentary in engine/battle/core.asm

### PR DESCRIPTION
**Pull request by xCrystal**
I'm doing a gen 1 mechanics research for smogon and Pokemon simulators, and I've been adding commentary to the disassembly simultaneously. I'm only researching mechanics that are relevant to competitve batlting, so I left out things like catching Pokemon, gaining experience, safari zone stuff etc. So far only a few move effects are covered but I'll hopefully get the rest done in the future (including those in different banks).

### CODE REVIEW

**Comment by dannye** [comment]
This is all very useful. I would just say that instead of changing every instance of "Func_3d80a" to "Func_3d80a ; player can't move this turn", you should just rename the function.

**Comment by xCrystal** [comment]
I just didn't bother renaming labels other than two that were misleading. I guess I can go ahead name some that are common

**Comment by dannye** [comment]
If you don't mind, it would be appreciated. As complete as pokered is getting, fuller comments and labels is a lot of the work that's left.

**Comment by iimarckus** [comment]
These latest commits break the build.

**Comment by xCrystal** [comment]
ok, the problem was a couple of duplicate labels. I compiled now myself, and it should be fine now

**Pull request merged**
