### PR TITLE
Use monster name string constants

### PR DESCRIPTION
**Pull request by dannye**

### CODE REVIEW

**Comment by huderlem** [comment]
One thing you could potentially add here is the starter name constants.

Something like:
`N_STARTER1 EQUS "CHARMANDER"`

**Comment by yenatch** [comment]
No. `N_RHYDON EQUS "CYNDAQUIL"` doesn't help anyone.

For string constants in general, you can do `"{N_BULBASAUR} ..."` instead of `N_BULBASAUR, " ..."`, and PokemonNames could have used a macro that uses `STRLEN()` to figure out how many `@`s to put.

Come to think of it... does this even work?

**Comment by huderlem** [comment]
yenatch, can please you clarify what you mean by the first thing you said?

"No. `N_RHYDON EQUS "CYNDAQUIL"` doesn't help anyone."

That isn't in any of the commits Danny added, and it doesn't seem related to my Starter name suggestion.

**Comment by yenatch** [comment]
N_STARTER1 is fine.

**Comment by huderlem** [comment]
Not sure if Github sends notifications for updating comments, but I edited my comment above with another suggestion.

**Comment by yenatch** [comment]
Right, but what's the pokedex number got to do with "RHYDON can lift up a mountain!"? Is "CYNDAQUIL can lift up a mountain!" any better?

**Comment by yenatch** [comment]
Moreover, does anyone actually want this?

**Comment by iimarckus** [comment]
Not a fan of this. Is there actually a use case for this change? It doesn’t seem like a very useful abstraction.

**Comment by barryanders** [comment]
I prefer the way that it is already, but I may be misunderstanding the purpose.

**Pull request closed without merging**
